### ISSUE TITLE
iOS 10 下那个view 的位置不对 

### ISSUE THREAD

**Issue by xiaohundan** [XiFengLang/JKNavigationController#1]
- (void)jp_setNavigationBarBackgroundColor:(UIColor *)color{
        [[self.subviews firstObject] insertSubview:self.backgroundView atIndex:0];
}
添加这一句 才行

**Comment by XiFengLang** [comment]
新的方案已经搞出来了，但是本地代码不小心被远程的覆盖了，新代码等几天吧

**Comment by XiFengLang** [comment]
2.0版已兼容iOS10
